name: chat-bot-dev

services:
  server:
    container_name: chat-bot-dev-server
    environment:
      NODE_ENV: development
      PORT: ${PORT:-3001}
    env_file:
      - ./.env.development
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
